name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn build
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: RemoveAllEmbeds.js
