name: Main

on: 
 push:
  tags:
   - v*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: RemoveAllEmbeds.js
